// This file will be generated by Supabase CLI later
// For now, we'll create a placeholder

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string | null
          display_name: string | null
          email: string | null
          avatar_id: string | null
          total_points: number
          current_level: number
          current_streak: number
          longest_streak: number
          tasks_completed: number
          notification_enabled: boolean
          notification_time: string
          language: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username?: string | null
          display_name?: string | null
          email?: string | null
          avatar_id?: string | null
          total_points?: number
          current_level?: number
          current_streak?: number
          longest_streak?: number
          tasks_completed?: number
          notification_enabled?: boolean
          notification_time?: string
          language?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string | null
          display_name?: string | null
          email?: string | null
          avatar_id?: string | null
          total_points?: number
          current_level?: number
          current_streak?: number
          longest_streak?: number
          tasks_completed?: number
          notification_enabled?: boolean
          notification_time?: string
          language?: string
          created_at?: string
          updated_at?: string
        }
      }
      // Add other tables as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
